# Importing Libraries 


In [24]:
!pip install opencv-python

     ---------------------------------------- 38.2/38.2 MB 8.2 MB/s eta 0:00:00


In [2]:
import numpy as np
import pandas as pd
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import seaborn as sb
import os 
import cv2
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import sympy

# Loading the Dataset


In [3]:
path_dir = os.listdir("C:/Users/pvdhe/OneDrive/Documents/extracted_images")

data = []
label = []
m=0
for each in path_dir:
    if(each.isdigit()):
        currentFolder = "C:/Users/pvdhe/OneDrive/Documents/extracted_images/" + each
        temp = 0
        for i, file in enumerate(os.listdir(currentFolder)):
            if(temp>=100):
                break
            im= cv2.imread((os.path.join(currentFolder, file)))
            img=cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
            resized_image = cv2.resize(img, (8,8))
            img  =  np.array(resized_image)
            img = img.ravel()
            img = img.tolist()
            data.append(img)
            label.append(m)
            temp+=1
        m+=1
df = pd.DataFrame(data)
df["label"] = label

df = df.sample(frac=1)
df.head()

0    1    2    3    4    5    6    7    8    9  ...   55   56   57  \
38   255  253  254  255  255  177  255  254  255   18  ...  255  255  255   
258  255  254  209  253  253  255  255  255  255  225  ...  255  255  255   
65   254   75  255  254  175  254  255  255  255  239  ...  255  255  255   
416  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
803  255  255  255  189  112  254  255  255  255  255  ...  255  255  255   

      58   59   60   61   62   63  label  
38   254  254  255  209  255  255      0  
258  112  255  255  255  255  255      2  
65   255  112  255  255  254  255      0  
416  255  255  255  255  255  255      4  
803  255  255   15  255  255  255      8  

[5 rows x 65 columns]

In [4]:
data = np.array(data)
label = np.array(label)
print(data)
print(label)

[[255 254 254 ... 253 255 255]
 [255 255 121 ... 254 255 255]
 [255 180 254 ...  77 255 255]
 ...
 [255 255 254 ... 254 255 255]
 [255 255 253 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3

In [5]:
df_new = df.sample(frac=1)
X_train, X_test, y_train, y_test = train_test_split(data,label,test_size = 0.2,random_state = 42)

In [6]:
clf = svm.SVC(kernel="linear")

In [7]:
clf.fit(X_train,y_train)

SVC(kernel='linear')

In [8]:
from sklearn.metrics import accuracy_score
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)


In [9]:
print(accuracy)

0.385
